-- =====================================================================
-- Draw & Guess word bank (English + Arabic). Run AFTER 0009_draw_and_guess.sql.
-- Concrete, drawable nouns across categories, tiered difficulty 1 (easy) .. 3 (hard).
-- Safe to re-run: it clears and reloads the word bank.
-- The Arabic entries are stored in natural spelling; guess matching folds
-- diacritics / alef / ta-marbuta variants via public.draw_normalize().
-- =====================================================================
truncate table public.draw_words;

-- ---------- English ----------
insert into public.draw_words (lang, word, category, difficulty) values
('en','cat','animals',1),
('en','dog','animals',1),
('en','fish','animals',1),
('en','horse','animals',1),
('en','lion','animals',1),
('en','camel','animals',1),
('en','snake','animals',1),
('en','elephant','animals',2),
('en','butterfly','animals',2),
('en','spider','animals',2),
('en','penguin','animals',2),
('en','octopus','animals',3),
('en','giraffe','animals',2),
('en','dolphin','animals',2),
('en','owl','animals',2),
('en','apple','food',1),
('en','banana','food',1),
('en','pizza','food',1),
('en','bread','food',1),
('en','egg','food',1),
('en','cake','food',1),
('en','coffee','food',1),
('en','ice cream','food',2),
('en','watermelon','food',2),
('en','hamburger','food',2),
('en','falafel','food',2),
('en','mansaf','food',3),
('en','hummus','food',2),
('en','sun','nature',1),
('en','moon','nature',1),
('en','star','nature',1),
('en','tree','nature',1),
('en','flower','nature',1),
('en','cloud','nature',1),
('en','mountain','nature',1),
('en','river','nature',2),
('en','rainbow','nature',2),
('en','volcano','nature',2),
('en','desert','nature',2),
('en','waterfall','nature',3),
('en','house','objects',1),
('en','car','objects',1),
('en','book','objects',1),
('en','chair','objects',1),
('en','clock','objects',1),
('en','key','objects',1),
('en','phone','objects',1),
('en','umbrella','objects',2),
('en','glasses','objects',2),
('en','ladder','objects',2),
('en','candle','objects',2),
('en','scissors','objects',2),
('en','guitar','objects',2),
('en','camera','objects',2),
('en','telescope','objects',3),
('en','lighthouse','objects',3),
('en','airplane','transport',1),
('en','boat','transport',1),
('en','train','transport',1),
('en','bicycle','transport',2),
('en','rocket','transport',2),
('en','helicopter','transport',2),
('en','submarine','transport',3),
('en','football','sports',1),
('en','swimming','sports',2),
('en','skateboard','sports',2),
('en','basketball','sports',2),
('en','tennis','sports',2),
('en','snowman','misc',1),
('en','robot','misc',1),
('en','ghost','misc',1),
('en','crown','misc',1),
('en','heart','misc',1),
('en','balloon','misc',1),
('en','kite','misc',2),
('en','castle','misc',2),
('en','pyramid','misc',2),
('en','treasure','misc',2),
('en','dragon','misc',2),
('en','mermaid','misc',3),
('en','windmill','misc',3),
('en','rainbow','misc',2),
('en','bridge','misc',2),
('en','Petra','jordan',2),
('en','Wadi Rum','jordan',3),
('en','Dead Sea','jordan',2),
('en','camel','jordan',1),
('en','olive tree','jordan',2),
('en','keffiyeh','jordan',3),
('en','tea','jordan',1),
('en','desert','jordan',2),
('en','doctor','people',2),
('en','king','people',1),
('en','clown','people',1),
('en','pirate','people',2),
('en','astronaut','people',2),
('en','chef','people',2),
('en','teacher','people',2),
('en','rain','nature',1),
('en','snow','nature',1),
('en','fire','nature',1),
('en','eye','body',1),
('en','hand','body',1),
('en','foot','body',1),
('en','tooth','body',1);

-- ---------- Arabic ----------
insert into public.draw_words (lang, word, category, difficulty) values
('ar','قطة','animals',1),
('ar','كلب','animals',1),
('ar','سمكة','animals',1),
('ar','حصان','animals',1),
('ar','أسد','animals',1),
('ar','جمل','animals',1),
('ar','ثعبان','animals',1),
('ar','فيل','animals',1),
('ar','فراشة','animals',2),
('ar','عنكبوت','animals',2),
('ar','بطريق','animals',2),
('ar','أخطبوط','animals',3),
('ar','زرافة','animals',2),
('ar','دلفين','animals',2),
('ar','بومة','animals',2),
('ar','تفاحة','food',1),
('ar','موزة','food',1),
('ar','بيتزا','food',1),
('ar','خبز','food',1),
('ar','بيضة','food',1),
('ar','كعكة','food',1),
('ar','قهوة','food',1),
('ar','بوظة','food',2),
('ar','بطيخ','food',2),
('ar','همبرغر','food',2),
('ar','فلافل','food',2),
('ar','منسف','food',3),
('ar','حمص','food',2),
('ar','شمس','nature',1),
('ar','قمر','nature',1),
('ar','نجمة','nature',1),
('ar','شجرة','nature',1),
('ar','زهرة','nature',1),
('ar','غيمة','nature',1),
('ar','جبل','nature',1),
('ar','نهر','nature',2),
('ar','قوس قزح','nature',2),
('ar','بركان','nature',2),
('ar','صحراء','nature',2),
('ar','شلال','nature',3),
('ar','بيت','objects',1),
('ar','سيارة','objects',1),
('ar','كتاب','objects',1),
('ar','كرسي','objects',1),
('ar','ساعة','objects',1),
('ar','مفتاح','objects',1),
('ar','هاتف','objects',1),
('ar','مظلة','objects',2),
('ar','نظارة','objects',2),
('ar','سلم','objects',2),
('ar','شمعة','objects',2),
('ar','مقص','objects',2),
('ar','جيتار','objects',2),
('ar','كاميرا','objects',2),
('ar','منظار','objects',3),
('ar','منارة','objects',3),
('ar','طائرة','transport',1),
('ar','قارب','transport',1),
('ar','قطار','transport',1),
('ar','دراجة','transport',2),
('ar','صاروخ','transport',2),
('ar','مروحية','transport',2),
('ar','غواصة','transport',3),
('ar','كرة قدم','sports',1),
('ar','سباحة','sports',2),
('ar','كرة سلة','sports',2),
('ar','تنس','sports',2),
('ar','رجل ثلج','misc',1),
('ar','روبوت','misc',1),
('ar','شبح','misc',1),
('ar','تاج','misc',1),
('ar','قلب','misc',1),
('ar','بالون','misc',1),
('ar','طائرة ورقية','misc',2),
('ar','قلعة','misc',2),
('ar','هرم','misc',2),
('ar','كنز','misc',2),
('ar','تنين','misc',2),
('ar','حورية البحر','misc',3),
('ar','طاحونة','misc',3),
('ar','جسر','misc',2),
('ar','البتراء','jordan',2),
('ar','وادي رم','jordan',3),
('ar','البحر الميت','jordan',2),
('ar','شجرة زيتون','jordan',2),
('ar','كوفية','jordan',3),
('ar','شاي','jordan',1),
('ar','طبيب','people',2),
('ar','ملك','people',1),
('ar','مهرج','people',1),
('ar','قرصان','people',2),
('ar','رائد فضاء','people',2),
('ar','طباخ','people',2),
('ar','معلم','people',2),
('ar','مطر','nature',1),
('ar','ثلج','nature',1),
('ar','نار','nature',1),
('ar','عين','body',1),
('ar','يد','body',1),
('ar','قدم','body',1),
('ar','سن','body',1);
